package authcompat_test

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"strings"
	"testing"
)

// Fixtures generated by doltlite's C credential signer (test/doltlite_creds_kat.c)
// for the fixed ed25519 seed 00..1f, audience "doltremoteapi.dolthub.com", and
// iat 1700000000. ed25519 signatures are deterministic, so these are stable.
//
// This token has also been validated through ld's actual server-side validator
// (go/libraries/jwtauth.ValidateJWTForVersion via go-jose); this test re-checks
// the same properties with only the standard library so the guard stays
// dependency-light. The invariants asserted here are exactly what ld's
// remoteauth enforces.
const (
	goldenJWT    = "eyJhbGciOiJFZERTQSIsImtpZCI6IjdrdTFjZ2Q3dWprY3JpNXU0c21tcnNycGNwM2Vqc21nYzl0N28zZGtkYmFycyIsImRvbHRfdG9rZW5fdmVyc2lvbiI6IjIwMjMuMDEifQ.eyJpc3MiOiJkb2x0LWNsaWVudC5kb2x0aHViLmNvbSIsInN1YiI6ImRvbHRDbGllbnRDcmVkZW50aWFscy83a3UxY2dkN3Vqa2NyaTV1NHNtbXJzcnBjcDNlanNtZ2M5dDdvM2RrZGJhcnMiLCJhdWQiOiJkb2x0cmVtb3RlYXBpLmRvbHRodWIuY29tIiwiaWF0IjoxNzAwMDAwMDAwLCJleHAiOjE3MDAwMDAwMzB9.zYNXsaON_rblUat4NuSeDYNcCkkn5V5M28BVXgTybOs4lldxD_GUxRroTTeKxlLebVONlBZxI6ukuhbW_1hvCg"
	goldenPubHex = "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
	goldenKid    = "7ku1cgd7ujkcri5u4smmrsrpcp3ejsmgc9t7o3dkdbars"

	// ld: go/libraries/remoteauth constants for the "new" token version.
	clientIssuer  = "dolt-client.dolthub.com"
	subjectPrefix = "doltClientCredentials/"
	tokenVersion  = "2023.01"
	wantAudience  = "doltremoteapi.dolthub.com"
)

type jwtHeader struct {
	Alg          string `json:"alg"`
	Kid          string `json:"kid"`
	TokenVersion string `json:"dolt_token_version"`
}

type jwtClaims struct {
	Iss string `json:"iss"`
	Sub string `json:"sub"`
	Aud string `json:"aud"`
	Iat int64  `json:"iat"`
	Exp int64  `json:"exp"`
}

func decodeSeg(t *testing.T, seg string) []byte {
	t.Helper()
	b, err := base64.RawURLEncoding.DecodeString(seg)
	if err != nil {
		t.Fatalf("base64url decode: %v", err)
	}
	return b
}

func pubKey(t *testing.T) ed25519.PublicKey {
	t.Helper()
	b, err := hex.DecodeString(goldenPubHex)
	if err != nil {
		t.Fatal(err)
	}
	return ed25519.PublicKey(b)
}

// TestDoltliteTokenMatchesDoltHubContract asserts the doltlite-produced token
// satisfies exactly what ld's remoteauth requires: EdDSA header with kid and
// dolt_token_version, the dolthub issuer, the expected audience, sub ==
// doltClientCredentials/<kid>, and a signature that verifies against the
// credential's ed25519 public key.
func TestDoltliteTokenMatchesDoltHubContract(t *testing.T) {
	parts := strings.Split(goldenJWT, ".")
	if len(parts) != 3 {
		t.Fatalf("expected 3 JWT segments, got %d", len(parts))
	}

	var h jwtHeader
	if err := json.Unmarshal(decodeSeg(t, parts[0]), &h); err != nil {
		t.Fatalf("header json: %v", err)
	}
	if h.Alg != "EdDSA" {
		t.Errorf("alg = %q, want EdDSA", h.Alg)
	}
	if h.Kid != goldenKid {
		t.Errorf("kid = %q, want %q", h.Kid, goldenKid)
	}
	if h.TokenVersion != tokenVersion {
		t.Errorf("dolt_token_version = %q, want %q", h.TokenVersion, tokenVersion)
	}

	var c jwtClaims
	if err := json.Unmarshal(decodeSeg(t, parts[1]), &c); err != nil {
		t.Fatalf("claims json: %v", err)
	}
	if c.Iss != clientIssuer {
		t.Errorf("iss = %q, want %q", c.Iss, clientIssuer)
	}
	if c.Aud != wantAudience {
		t.Errorf("aud = %q, want %q", c.Aud, wantAudience)
	}
	if c.Sub != subjectPrefix+goldenKid {
		t.Errorf("sub = %q, want %q", c.Sub, subjectPrefix+goldenKid)
	}
	if c.Exp != c.Iat+30 {
		t.Errorf("exp-iat = %d, want 30", c.Exp-c.Iat)
	}

	// Signature covers "<header>.<claims>".
	signingInput := []byte(parts[0] + "." + parts[1])
	sig := decodeSeg(t, parts[2])
	if len(sig) != ed25519.SignatureSize {
		t.Fatalf("signature length = %d, want %d", len(sig), ed25519.SignatureSize)
	}
	if !ed25519.Verify(pubKey(t), signingInput, sig) {
		t.Fatal("ed25519 signature did not verify against the credential public key")
	}
}

func TestTamperedTokenFailsVerification(t *testing.T) {
	parts := strings.Split(goldenJWT, ".")
	sig := decodeSeg(t, parts[2])
	sig[0] ^= 0xff // corrupt the signature
	signingInput := []byte(parts[0] + "." + parts[1])
	if ed25519.Verify(pubKey(t), signingInput, sig) {
		t.Fatal("expected corrupted signature to fail verification")
	}

	// Corrupting the signed content must also fail.
	badInput := []byte(parts[0] + "." + parts[1] + "x")
	goodSig := decodeSeg(t, parts[2])
	if ed25519.Verify(pubKey(t), badInput, goodSig) {
		t.Fatal("expected altered signing input to fail verification")
	}
}
